version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radio_app
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: radio_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: radio
      MYSQL_USER: radio_user
      MYSQL_PASSWORD: radio_pass
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
